version: '3.8'

services:
  db:
    image: ankane/pgvector
    container_name: data-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
