version: '3.8'

services:
  db:
    image: ankane/pgvector
    container_name: data-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data
    volumes:
      - pgdata:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5.22-enterprise
    container_name: neo4j-kg-enterprise
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_server_memory_heap_initial__size: 2G
      NEO4J_server_memory_heap_max__size: 2G
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    volumes:
      # Reattach the existing named volume
      - f95d8a60b5e8ed9d725bfd82fc7691d4e6e5e0177a527921fa12d640a97e8eb0:/data

volumes:
  pgdata:
  f95d8a60b5e8ed9d725bfd82fc7691d4e6e5e0177a527921fa12d640a97e8eb0:
    external: true