"""add trigram index on job_titles

Revision ID: 66f51c6e48cf
Revises: 7569315c4503
Create Date: 2025-07-15 08:04:01.382156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f51c6e48cf'
down_revision: Union[str, Sequence[str], None] = '7569315c4503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('job_titles_title_trgm_idx', 'job_titles', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('job_titles_title_trgm_idx', table_name='job_titles', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    # ### end Alembic commands ###
